### ISSUE TITLE
parameters to query

### ISSUE THREAD

**Issue by drewp** [tomayac/ldf-client#3]
```
<ldf-client response-format="streaming" auto start-fragment="../data" query="
  PREFIX : <https://whopickedthis.com/ns#>
  SELECT DISTINCT ?p ?o WHERE {
             <help> a :User; ?p ?o .
                   }">
       </ldf-client>
```

To set a subject for that user, it seems like I have to move to javascript and set 'query' from there somehow, which is a big hurdle for a page that could be just a bunch of polymer elements stitched together with attribute bindings. 

Here's the API I'm picturing:

```
<ldf-client ... var-user="{{user}}" query="
  PREFIX : <https://whopickedthis.com/ns#>
  SELECT DISTINCT ?p ?o WHERE {
             ?user a :User; ?p ?o .
                   }">
       </ldf-client>
```

where attributes starting with 'var-' turn into initial bindings to the sparql query.

**Comment by tomayac** [comment]
If I am not completely wrong, in order for Polymer to recognize attributes, they have to be [declared beforehand](https://www.polymer-project.org/1.0/docs/devguide/properties.html). One could, however, imagine a micro syntax in an attribute `sparql-bindings` (or similar) that would somehow be mapped to the variables in the `query` attribute. I have too little practical experience with SPARQL to design this micro syntax. Do you, or maybe @RubenVerborgh have anything in mind that could work, ideally something that already exists?

**Comment by RubenVerborgh** [comment]
The first thing that comes to mind is [`VALUES`](http://www.w3.org/TR/sparql11-query/#inline-data). However, I'd still have to write support for it then in the client.

Alternatively, the [SPARQL.js](https://github.com/RubenVerborgh/SPARQL.js) parser (which is included in the bundle because Client.js uses it) provides a query _generator_ as well. So the query could be parsed, the variable replaced, and the query be regenerated again.
